export enum Environment {
  DISCORD_TOKEN = 'DISCORD_TOKEN',
  DISCORD_CLIENT = 'DISCORD_CLIENT',
  DISCORD_TEST_GUILD = 'DISCORD_TEST_GUILD',
  MONGO_ATLAS = 'MONGO_ATLAS',
  SERVER_PORT = 'SERVER_PORT',
  TWITCH_CLIENT = 'TWITCH_CLIENT',
  TWITCH_SECRET = 'TWITCH_SECRET',
  TWITCH_VERIFICATION_SECRET = 'TWITCH_VERIFICATION_SECRET',
}
